environment:
  key-store-password:
    secure: pGrDZahzdzmTIoHkPspWbQ==    
  SONARQUBE_TOKEN:
    secure: DSwAr4fYt3Q35Sjob5qAN5ujYqFCPZQguJ2yhI3IN46AIK63sRLhpamof6BZr9lx
before_build:
- nuget restore
- appveyor-retry dotnet restore -v Minimal
build:
  project: CanoePoloLeagueOrganiser.sln 
  verbosity: quiet
after_test:
- msbuild /verbosity:quiet "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=cuddlyburger" "/p:AndroidSigningKeyPass=%key-store-password%" "/p:AndroidSigningKeyStore=CanoePoloLeageOrganiserAndroidKey" "/p:AndroidSigningStorePass=%key-store-password%"  ".\CanoePoloLeagueOrganiserXamarin\CanoePoloLeagueOrganiserXamarin.csproj"
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"CanoePoloLeagueOrganiserTests\bin\Debug\CanoePoloLeagueOrganiserTests.dll -noshadow -appveyor"  -output:.\CanoePoloLeagueOrganiser_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "CanoePoloLeagueOrganiser_coverage.xml"
artifacts:
  - path: CanoePoloLeagueOrganiserXamarin\bin\Release\com.canoe_polo_organisr-Signed.apk
# choosing builds to deploy via appveyor environment now, instead of automatically on tag, which seemed to go a bit funny
#deploy:
#  release: CanoePoloOrganisr-v$(appveyor_build_version)
#  description: 'CanoePoloOrganisr'
#  provider: GitHub
#  auth_token:
#    secure:  # encrypted auth token from GitHub
#  artifact: CanoePoloLeagueOrganiserXamarin\bin\Release\com.canoe_polo_organisr-Signed.apk
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only
