environment:
  key-store-password:
    secure: pGrDZahzdzmTIoHkPspWbQ==    
before_build:
- nuget restore
- appveyor-retry dotnet restore -v Minimal
build:
  project: CanoePoloLeagueOrganiser.sln 
  verbosity: quiet
after_test:
- msbuild /verbosity:quiet "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=cuddlyburger" "/p:AndroidSigningKeyPass=%key-store-password%" "/p:AndroidSigningKeyStore=CanoePoloLeageOrganiserAndroidKey" "/p:AndroidSigningStorePass=%key-store-password%"  ".\CanoePoloLeagueOrganiserXamarin\CanoePoloLeagueOrganiserXamarin.csproj"
artifacts:
  - path: CanoePoloLeagueOrganiserXamarin\bin\Release\com.canoe_polo_organisr-Signed.apk
